### PR TITLE
Hebrew translation

### PR DESCRIPTION
**Pull request by leac**
Please see if you can add this Hebrew translation PR

Kindly,
Lea
ORT Israel

### CODE REVIEW

**Comment by sensei-hacker** [comment]
Thanks for submitting this!

Similar to the other one, please ask someone other than the original developer to QA this by applying the commit and verifying and that both English and Hebrew work correctly after the change.  If that's already been done, just let me know. Thanks.

**Comment by leac** [comment]
@nadavkav Would you mind QA-ing this?

**Comment by nadavkav** [comment]
With pleasure :smile: ...

**Comment by nadavkav** [comment]
This one looks great too +1

**Pull request merged**
